apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: rabbitmq-in-cluster
entity:
  name: rabbitmq-in-cluster
  type: amqp
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        init: |-
          name: rabbitmq-{{ randAlpha 5 | lower}}
          port: 5672
          username: username
          password: password
        manifests: |-
          {{ .resource.id }}-deployment.yaml:
            location: namespace
            data:
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: {{ .init.name }}
              spec:
                serviceName: {{ .init.name }}
                replicas: 1
                selector:
                  matchLabels:
                    app: {{ .init.name }}
                template:
                  metadata:
                    labels:
                      app: {{ .init.name }}
                  spec:
                    nodeSelector:
                      "kubernetes.io/os": linux
                    containers:
                    - name: {{ .init.name }}
                      image: mcr.microsoft.com/mirror/docker/library/rabbitmq:3.10-management-alpine
                      ports:
                      - containerPort: {{ .init.port }}
                        name: rabbitmq-amqp
                      - containerPort: 15672
                        name: rabbitmq-http
                      env:
                      - name: RABBITMQ_DEFAULT_USER
                        value: {{ .init.username }}
                      - name: RABBITMQ_DEFAULT_PASS
                        value: {{ .init.password }}
                      resources:
                        requests:
                          cpu: 10m
                          memory: 128Mi
                        limits:
                          cpu: 250m
                          memory: 256Mi
                      volumeMounts:
                      - name: rabbitmq-enabled-plugins
                        mountPath: /etc/rabbitmq/enabled_plugins
                        subPath: enabled_plugins
                    volumes:
                    - name: rabbitmq-enabled-plugins
                      configMap:
                        name: {{ .init.name }}
                        items:
                        - key: rabbitmq_enabled_plugins
                          path: enabled_plugins
          {{ .resource.id }}-configmap.yaml:
            location: namespace
            data:
              apiVersion: v1
              data:
                rabbitmq_enabled_plugins: |
                  [rabbitmq_management,rabbitmq_prometheus,rabbitmq_amqp1_0].
              kind: ConfigMap
              metadata:
                name: {{ .init.name }}
          {{ .resource.id }}-service.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: Service
              metadata:
                name: {{ .init.name }}
              spec:
                selector:
                  app: {{ .init.name }}
                ports:
                  - name: rabbitmq-amqp
                    port: {{ .init.port }}
                    targetPort: {{ .init.port }}
                  - name: rabbitmq-http
                    port: 15672
                    targetPort: 15672
                type: ClusterIP
        outputs: |
          host: {{ .init.name }}
          port: {{ .init.port }}
        secrets: |
          username: {{ .init.username }}
          password: {{ .init.password }}
  criteria:
    - {}