apiVersion: config.humanitec.io/v1b1
kind: ScoreDeployConfig
workloads:
  - specFile: ./order-service/score.yaml
    extensionsFile: ./order-service/humanitec.score.yaml
  - specFile: ./product-service/score.yaml
    extensionsFile: ./product-service/humanitec.score.yaml
  - specFile: ./store-front/score.yaml
    extensionsFile: ./store-front/humanitec.score.yaml
  - specFile: ./makeline-service/score.yaml
    extensionsFile: ./makeline-service/humanitec.score.yaml
  - specFile: ./store-admin/score.yaml
    extensionsFile: ./store-admin/humanitec.score.yaml